# Generated by Django 5.2.3 on 2025-06-16 20:38

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="EscapeRoom",
            fields=[
                ("id_escape_room", models.AutoField(primary_key=True, serialize=False)),
                (
                    "nazev",
                    models.CharField(max_length=100, verbose_name="Název místnosti"),
                ),
                (
                    "obtiznost",
                    models.CharField(max_length=45, verbose_name="Obtížnost"),
                ),
                (
                    "strasidelnost",
                    models.CharField(max_length=45, verbose_name="Strašidelnost"),
                ),
                (
                    "cena",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Cena"
                    ),
                ),
                (
                    "doporuceny_vek",
                    models.CharField(max_length=45, verbose_name="Doporučený věk"),
                ),
                (
                    "tema",
                    models.CharField(max_length=45, unique=True, verbose_name="Téma"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Vytvořeno"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Aktualizováno"),
                ),
            ],
            options={
                "verbose_name": "Úniková místnost",
                "verbose_name_plural": "Únikové místnosti",
            },
        ),
        migrations.CreateModel(
            name="Herec",
            fields=[
                ("id_herec", models.AutoField(primary_key=True, serialize=False)),
                ("jmeno", models.CharField(max_length=45, verbose_name="Jméno")),
                ("prijmeni", models.CharField(max_length=45, verbose_name="Příjmení")),
                ("role", models.CharField(max_length=45, verbose_name="Role")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Vytvořeno"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Aktualizováno"),
                ),
            ],
            options={
                "verbose_name": "Herec",
                "verbose_name_plural": "Herci",
            },
        ),
        migrations.CreateModel(
            name="Lokace",
            fields=[
                ("id_lokace", models.AutoField(primary_key=True, serialize=False)),
                (
                    "nazev",
                    models.CharField(
                        max_length=45, unique=True, verbose_name="Název lokace"
                    ),
                ),
                ("mesto", models.CharField(max_length=45, verbose_name="Město")),
                ("ulice", models.CharField(max_length=45, verbose_name="Ulice")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Vytvořeno"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Aktualizováno"),
                ),
            ],
            options={
                "verbose_name": "Lokace",
                "verbose_name_plural": "Lokace",
            },
        ),
        migrations.CreateModel(
            name="Spravce",
            fields=[
                ("id_spravce", models.AutoField(primary_key=True, serialize=False)),
                ("jmeno", models.CharField(max_length=45, verbose_name="Jméno")),
                ("prijmeni", models.CharField(max_length=45, verbose_name="Příjmení")),
                ("vek", models.IntegerField(verbose_name="Věk")),
                (
                    "doba_zamestnani",
                    models.CharField(
                        blank=True,
                        max_length=45,
                        null=True,
                        verbose_name="Doba zaměstnání",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Vytvořeno"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Aktualizováno"),
                ),
            ],
            options={
                "verbose_name": "Správce",
                "verbose_name_plural": "Správci",
            },
        ),
        migrations.CreateModel(
            name="Zakaznik",
            fields=[
                ("id_zakaznik", models.AutoField(primary_key=True, serialize=False)),
                ("jmeno", models.CharField(max_length=45, verbose_name="Jméno")),
                ("prijmeni", models.CharField(max_length=45, verbose_name="Příjmení")),
                (
                    "telefon",
                    models.CharField(
                        max_length=45, unique=True, verbose_name="Telefon"
                    ),
                ),
                (
                    "email",
                    models.EmailField(max_length=45, unique=True, verbose_name="Email"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Vytvořeno"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Aktualizováno"),
                ),
            ],
            options={
                "verbose_name": "Zákazník",
                "verbose_name_plural": "Zákazníci",
            },
        ),
        migrations.CreateModel(
            name="HerciHasRecenze",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Vytvořeno"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Aktualizováno"),
                ),
                (
                    "herec",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="booking.herec"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="HerciHasEscapeRoom",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Vytvořeno"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Aktualizováno"),
                ),
                (
                    "escape_room",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="booking.escaperoom",
                    ),
                ),
                (
                    "herec",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="booking.herec"
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="escaperoom",
            name="herci",
            field=models.ManyToManyField(
                blank=True,
                through="booking.HerciHasEscapeRoom",
                to="booking.herec",
                verbose_name="Herci",
            ),
        ),
        migrations.AddField(
            model_name="escaperoom",
            name="lokace",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="booking.lokace",
                verbose_name="Lokace",
            ),
        ),
        migrations.CreateModel(
            name="Recenze",
            fields=[
                ("id_recenze", models.AutoField(primary_key=True, serialize=False)),
                (
                    "datum",
                    models.DateField(
                        default=django.utils.timezone.now, verbose_name="Datum"
                    ),
                ),
                ("autor", models.CharField(max_length=45, verbose_name="Autor")),
                ("obsah", models.CharField(max_length=255, verbose_name="Obsah")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Vytvořeno"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Aktualizováno"),
                ),
                (
                    "herci",
                    models.ManyToManyField(
                        blank=True,
                        through="booking.HerciHasRecenze",
                        to="booking.herec",
                        verbose_name="Herci",
                    ),
                ),
            ],
            options={
                "verbose_name": "Recenze",
                "verbose_name_plural": "Recenze",
            },
        ),
        migrations.AddField(
            model_name="hercihasrecenze",
            name="recenze",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="booking.recenze"
            ),
        ),
        migrations.CreateModel(
            name="RecenzeHasEscapeRoom",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Vytvořeno"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Aktualizováno"),
                ),
                (
                    "escape_room",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="booking.escaperoom",
                    ),
                ),
                (
                    "recenze",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="booking.recenze",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="recenze",
            name="escape_room",
            field=models.ManyToManyField(
                blank=True,
                through="booking.RecenzeHasEscapeRoom",
                to="booking.escaperoom",
                verbose_name="Únikové místnosti",
            ),
        ),
        migrations.AddField(
            model_name="lokace",
            name="spravce",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="booking.spravce",
                verbose_name="Správce",
            ),
        ),
        migrations.CreateModel(
            name="Rezervace",
            fields=[
                ("id_rezervace", models.AutoField(primary_key=True, serialize=False)),
                ("datum_rezervace", models.DateField(verbose_name="Datum rezervace")),
                ("cas_rezervace", models.TimeField(verbose_name="Čas rezervace")),
                ("pocet_hracu", models.IntegerField(verbose_name="Počet hráčů")),
                (
                    "poznamky",
                    models.TextField(blank=True, null=True, verbose_name="Poznámky"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Vytvořeno"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Aktualizováno"),
                ),
                (
                    "escape_room",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="booking.escaperoom",
                        verbose_name="Úniková místnost",
                    ),
                ),
                (
                    "zakaznik",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="booking.zakaznik",
                        verbose_name="Zákazník",
                    ),
                ),
            ],
            options={
                "verbose_name": "Rezervace",
                "verbose_name_plural": "Rezervace",
                "unique_together": {
                    ("datum_rezervace", "cas_rezervace", "escape_room")
                },
            },
        ),
    ]
