# Generated by Django 5.2.2 on 2025-06-17 22:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("booking", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="hercihasescaperoom",
            options={
                "verbose_name": "Herec a místnost",
                "verbose_name_plural": "Herci a místnosti",
            },
        ),
        migrations.AlterModelOptions(
            name="hercihasrecenze",
            options={
                "verbose_name": "Herec v recenzi",
                "verbose_name_plural": "Herci v recenzích",
            },
        ),
        migrations.AlterModelOptions(
            name="recenzehasescaperoom",
            options={
                "verbose_name": "Recenze a místnost",
                "verbose_name_plural": "Recenze a místnosti",
            },
        ),
        migrations.AlterUniqueTogether(
            name="hercihasescaperoom",
            unique_together={("herec", "escape_room")},
        ),
        migrations.AlterUniqueTogether(
            name="hercihasrecenze",
            unique_together={("herec", "recenze")},
        ),
        migrations.AlterUniqueTogether(
            name="recenzehasescaperoom",
            unique_together={("recenze", "escape_room")},
        ),
    ]
